#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="konnect"

mkdir -p "${CONFIG_PATH}"
configure_logging

print_debug "Configuring Konnect"
configure_konnect
print_debug "Finished Configuring Konnect"

liftoff
